print('輸入您理想的圓半徑，再按下Enter，我就會計算出周長&面積')
name = input('半徑?')
X = float(name)
print(type(name))
print(name)
print(type(X))
print('您輸入的理想半徑')
print(X)
print('答案一')
print('圓周長')
print(X*2*3.14159)
print('答案二')
print('圓面積')
print(X*X*3.14159)
print('感謝您的使用!')
Y = input('請問尊姓大名?')
print(Y)
print('是個很好的名字!')