a = int(input('第一個成績?'))
b = int(input('第二個成績?'))
c = int(input('第三個成績?'))
d = int(input('第四個成績?'))
data = []
data.append(a)
data.append(b)
data.append(c)
data.append(d)
maximum = max(data)
minimum = min(data)
summation = sum(data)
print('最大:',maximum)
print('最小:',minimum)
print('總和:',summation)
print('平均:',summation/4)